- hosts: all
  become: yes
  tasks:
  - name: Install apache 
    ansible.builtin.apt:  # = sudo apt install apache2
      name: [apache2, tree, wget, git, unzip]
      state: present
      update_cache: yes