- hosts: all
  vars:
    packages: 
      - tree
      - apache2
      - wget
      - git
      - unzip
  become: yes
  tasks:
  - name: Install apache 
    ansible.builtin.apt:  # = sudo apt install apache2
      name: "{{ packages }}"
      state: present