- hosts: all
  become: yes
  tasks:
  - name: Install apache 
    ansible.builtin.apt:  # = sudo apt install apache2
      name: [apache2, tree, wget, git, unzip]
      state: present
      update_cache: yes
    notify: Restart service apache
 
  handlers:
  - name: Restart service apache
    ansible.builtin.service:  # = systemctl start apache2
      name: apache2
      state: restarted
      enabled: yes
